create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (autor_id bigint not null, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table book add constraint FKm8b22qs8l1mpy0md6dncw3jpd foreign key (autor_id) references autor (id);
create table autor (id bigint not null auto_increment, nombre varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, book_id bigint not null, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table autor_has_book add constraint FK1p7ymyck3c4vh4i3fgpqfga9c foreign key (book_id) references book (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, book_id bigint not null, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table autor_has_book add constraint FK1p7ymyck3c4vh4i3fgpqfga9c foreign key (book_id) references book (id);
create table autor (id bigint not null auto_increment, nombre_completo varchar(255), primary key (id)) engine=InnoDB;
create table autor_has_book (autor_id bigint, book_id bigint not null, id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
create table book (id bigint not null auto_increment, isbn varchar(255), titulo varchar(255), primary key (id)) engine=InnoDB;
alter table autor_has_book add constraint FKjq64ao0k39h922127ugjgq5qg foreign key (autor_id) references autor (id);
alter table autor_has_book add constraint FK1p7ymyck3c4vh4i3fgpqfga9c foreign key (book_id) references book (id);
